#!/usr/bin/env python3
"""Extracts ROM entry-point addresses from cpu6502/rom/tmp/firmware.lbl into a JS constants file."""
import re
import sys

WANTED = [
    "SHELL_ENTRY", "SHELL_PROMPT", "START_WOZ",
    # bios.s's OS-call jump table, shown in the Help panel's OS calls section
    "PRINT_CHAR", "PRINT_STR", "LCD_PUTC", "LCD_PUTS", "LCD_CLEAR", "LCD_LINE1", "LCD_LINE2",
    "READ_KEY",
]
# SRC_START/SYM_START/OBJ_START ($3000/$2C00/$0400) are `=` constants in
# editor.s, not labels, so they're absent from firmware.lbl. The Help panel
# documents them as static text.


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <firmware.lbl> <out.js>")
    lbl_path, out_path = sys.argv[1], sys.argv[2]

    found = {}
    with open(lbl_path) as f:
        for line in f:
            m = re.match(r"al ([0-9A-Fa-f]+) \.(\w+)", line)
            if not m:
                continue
            addr, name = m.group(1), m.group(2)
            if name in WANTED:
                found[name] = int(addr, 16)

    missing = [n for n in WANTED if n not in found]
    if missing:
        sys.exit(f"gen_entrypoints.py: missing symbols in {lbl_path}: {missing}")

    with open(out_path, "w") as f:
        f.write("// Generated by gen_entrypoints.py from cpu6502/rom/tmp/firmware.lbl --\n")
        f.write("// do not edit by hand; regenerated by `make roms`.\n")
        f.write("window.CGOAC_ENTRYPOINTS = {\n")
        for name in WANTED:
            f.write(f"  {name}: 0x{found[name]:04X},\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
